import pandas as pd

df = pd.read_csv('/Users/matthewfalcona/FalconaForecast/datasets/top5_sched_21-22.csv')

df_norm = df

# serie a
df_norm = df_norm.replace('Atalanta BC','Atalanta', regex=True)
df_norm = df_norm.replace('Hellas Verona FC','HellasVerona', regex=True)
df_norm = df_norm.replace('Hellas Verona','HellasVerona', regex=True)
df_norm = df_norm.replace('Inter Milan','Inter', regex=True)
df_norm = df_norm.replace('AC Milan','Milan', regex=True)
df_norm = df_norm.replace('AS Roma','Roma', regex=True)

# buli
df_norm = df_norm.replace('Arminia Bielefeld','Arminia', regex=True)
df_norm = df_norm.replace('VfL Bochum','Bochum', regex=True)
df_norm = df_norm.replace('Bayern Munich','Bayern', regex=True)
df_norm = df_norm.replace('Borussia Dortmund','Dortmund', regex=True)
df_norm = df_norm.replace("Düsseldorf", "Dusseldorf", regex = True)
df_norm = df_norm.replace('SC Freiburg','Freiburg', regex=True)
df_norm = df_norm.replace('Eintracht Frankfurt','Frankfurt', regex=True)
df_norm = df_norm.replace("Eint Frankfurt", "Frankfurt", regex = True)
df_norm = df_norm.replace('Borussia Monchengladbach','Gladbach', regex=True)
df_norm = df_norm.replace("M'Gladbach", "Gladbach", regex = True)
df_norm = df_norm.replace('Greuther Fürth','GreutherFurth', regex=True)
df_norm = df_norm.replace("Hannover 96", "Hannover", regex = True)
df_norm = df_norm.replace("Hamburger SV", "Hamburg", regex = True)
df_norm = df_norm.replace("Hertha BSC", "Hertha", regex = True)
df_norm = df_norm.replace('Hertha Berlin','Hertha', regex=True)
df_norm = df_norm.replace('TSG Hoffenheim','Hoffenheim', regex=True)
df_norm = df_norm.replace('FC Koln','Koln', regex=True)
df_norm = df_norm.replace("Köln", "Koln", regex = True)
df_norm = df_norm.replace('Bayer Leverkusen','Leverkusen', regex=True)
df_norm = df_norm.replace('FSV Mainz 05','Mainz', regex=True)
df_norm = df_norm.replace("Mainz 05", "Mainz", regex = True)
df_norm = df_norm.replace("Paderborn 07", "Paderborn", regex = True)
df_norm = df_norm.replace('RB Leipzig','RBLeipzig', regex=True)
df_norm = df_norm.replace("Schalke 04", "Schalke", regex = True)
df_norm = df_norm.replace('VfB Stuttgart','Stuttgart', regex=True)
df_norm = df_norm.replace('Union Berlin','UnionBerlin', regex=True)
df_norm = df_norm.replace("Werder Bremen", "WerderBremen", regex = True)
df_norm = df_norm.replace('VfL Wolfsburg','Wolfsburg', regex=True)

# epl
df_norm = df_norm.replace('Aston Villa','AstonVilla', regex=True)
df_norm = df_norm.replace('Brighton and Hove Albion','Brighton', regex=True)
df_norm = df_norm.replace("Cardiff City", "Cardiff", regex = True)
df_norm = df_norm.replace('Crystal Palace','CrystalPalace', regex=True)
df_norm = df_norm.replace('Leeds United','LeedsUtd', regex=True)
df_norm = df_norm.replace('Leicester City','Leicester', regex=True)
df_norm = df_norm.replace('Manchester City','ManCity', regex=True)
df_norm = df_norm.replace("Manchester Utd", "ManUtd", regex = True)
df_norm = df_norm.replace('Manchester United','ManUtd', regex=True)
df_norm = df_norm.replace('Norwich City','NorwichCity', regex=True)
df_norm = df_norm.replace('Newcastle United','Newcastle', regex=True)
df_norm = df_norm.replace("Sheffield Utd", "SheffieldUtd", regex = True)
df_norm = df_norm.replace("Stoke City", "StokeCity", regex = True)
df_norm = df_norm.replace("Swansea City", "Swansea", regex = True)
df_norm = df_norm.replace('Tottenham Hotspur','Tottenham', regex=True)
df_norm = df_norm.replace("West Brom", "WestBrom", regex = True)
df_norm = df_norm.replace('West Ham United','WestHam', regex=True)
df_norm = df_norm.replace("West Ham", "WestHam", regex = True)
df_norm = df_norm.replace('Wolverhampton Wanderers','Wolves', regex=True)

#ligue 1
df_norm = df_norm.replace("Clermont Foot", "Clermont", regex = True)
df_norm = df_norm.replace('RC Lens','Lens', regex=True)
df_norm = df_norm.replace('AS Monaco','Monaco', regex=True)
df_norm = df_norm.replace("Nîmes", "Nimes", regex = True)
df_norm = df_norm.replace('Paris Saint Germain','PSG', regex=True)
df_norm = df_norm.replace("Paris S-G", "PSG", regex = True)
df_norm = df_norm.replace('Stade de Reims','Reims', regex=True)
df_norm = df_norm.replace("Saint-Étienne", "Saint-Etienne", regex = True)
df_norm = df_norm.replace('Saint Etienne','Saint-Etienne', regex=True)

#la liga
df_norm = df_norm.replace('Alavés','Alaves', regex=True)
df_norm = df_norm.replace('Atlético Madrid','Atletico', regex=True)
df_norm = df_norm.replace("Athletic Club", "AthleticBilbao", regex = True)
df_norm = df_norm.replace('Athletic Bilbao','AthleticBilbao', regex=True)
df_norm = df_norm.replace('Real Betis','Betis', regex=True)
df_norm = df_norm.replace('Cádiz CF','Cadiz', regex=True)
df_norm = df_norm.replace("Cádiz", "Cadiz", regex = True)
df_norm = df_norm.replace('Celta Vigo','CeltaVigo', regex=True)
df_norm = df_norm.replace('Elche CF','Elche', regex=True)
df_norm = df_norm.replace('Granada CF','Granada', regex=True)
df_norm = df_norm.replace("Leganés", "Leganes", regex = True)
df_norm = df_norm.replace("La Coruña", "LaCoruna", regex = True)
df_norm = df_norm.replace("Las Palmas", "LasPalmas", regex = True)
df_norm = df_norm.replace("Málaga", "Malaga", regex = True)
df_norm = df_norm.replace('CA Osasuna','Osasuna', regex=True)
df_norm = df_norm.replace('Rayo Vallecano','RayoVallecano', regex=True)
df_norm = df_norm.replace('Real Sociedad','RealSociedad', regex=True)
df_norm = df_norm.replace('Real Madrid','RealMadrid', regex=True)


forecast_sched = forecast_sched.replace("Nott'ham Forest", "Forest", regex=True)
forecast_sched = forecast_sched.replace('Nottingham Forest','Forest', regex=True)
forecast_sched = forecast_sched.replace('Werder Bremen','WerderBremen', regex=True)
forecast_sched = forecast_sched.replace('Almería','Almeria', regex=True)

pd.DataFrame(df_norm).to_csv('/Users/matthewfalcona/FalconaForecast/datasets/top5_sched_21-22.csv')